version: '3.8'
services:
  app:
    build: ./
    container_name: app
    command: sh -c "yarn run dev -- --host"
    ports:
      - '5173:5173'
    volumes:
      - './:/app'
    tty: true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: local
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 1s
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
